[phases]
setup = { pkgs = ["python3", "gcc", "python3-pip"] }  # Correct package specification

[phases.install]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"
]

[start]
command = "./start.sh"