[phases]
setup = "python3, gcc, python3-pip"  # Added explicit pip

[phases.install]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"  # Added pip upgrade
]

[start]
command = "bash ./start.sh"  # Explicit bash interpreter